name: Docker Image CI

on:
  push:
    branches:
    - main
    - solution
  pull_request:
    branches: 
    - main
    - solution

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pytime:$(date +%s)

