name: Docker Image CI and Push to hub 

on:
  push:
    branches:
    - main
    - solution
  pull_request:
    branches: 
    - main
    - solution

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out repo

    - name: Login to Dockerhub 
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytime:${{ GITHUB_RUN_ID }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
